# fly.toml file generated for sl-discordbot on 2023-01-16T17:42:34+01:00

app = "sl-discordbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true